 



CREATE FUNCTION ARROUND (@NUM FLOAT, @DEC INT)
RETURNS FLOAT
AS
BEGIN
   DECLARE @S_NUM VARCHAR(15),@AUX VARCHAR(15),@AUX1 VARCHAR(15), @DIGT INT, @RES FLOAT, @ARR INT

   SET @S_NUM = CONVERT(VARCHAR(15),@NUM)
   SET @ARR =   SUBSTRING(@S_NUM,CHARINDEX(@S_NUM,'.') + 3 + @DEC,CHARINDEX(@S_NUM,'.') + 3 + @DEC)
   SET @AUX = LEFT(@S_NUM,CHARINDEX(@S_NUM,'.') + 2 + @DEC)
--PRINT @S_NUM
--PRINT @AUX
--PRINT CONVERT(VARCHAR(10),@ARR)
 SET @AUX1= '0.0'
IF (@ARR >= 5)
   BEGIN
      SET @AUX1= @AUX1 + REPLICATE('0',@DEC -2)+1     
   END
--PRINT @AUX1
--PRINT @AUX
SET @RES = CONVERT(FLOAT,@AUX) + CONVERT(FLOAT,@AUX1)
--PRINT CONVERT(VARCHAR(10),@RES)   

   RETURN(@res)
END


SELECT dbo.ARROUND(45.78945,3)