SELECT  'IF (EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = ' + CHAR(39) + NAME + CHAR(39) + '))     DROP TABLE ' + NAME 
FROM SYS.TABLES
WHERE NAME LIKE '%_LOG'



SELECT  'IF (EXISTS (SELECT 1 FROM SYS.triggers WHERE NAME = ' + CHAR(39) + NAME + CHAR(39) + '))     DROP TRIGGER ' + NAME 
FROM SYS.triggers
WHERE NAME LIKE 'tr_upda%_LOG'



SELECT  'IF (EXISTS (SELECT 1 FROM SYS.PROCEDURES WHERE NAME = ' + CHAR(39) + NAME + CHAR(39) + '))     DROP PROCEDURE ' + NAME 
FROM SYS.PROCEDURES
WHERE NAME LIKE 'tr_upda%_LOG'




SELECT  'IF (EXISTS (SELECT 1 FROM SYS.VIEWS WHERE NAME = ' + CHAR(39) + NAME + CHAR(39) + '))     DROP VIEW ' + NAME 
FROM SYS.VIEWS
WHERE NAME LIKE 'VW%'





