
CREATE OR ALTER VIEW VW_ESTRUTURA_TABELA AS 
SELECT TABLE_NAME AS TABELA,ORDINAL_POSITION AS POSICAO,
       COLUMN_NAME +  ' ' + DATA_TYPE  +  ' ' + 
	   CASE WHEN CHARACTER_MAXIMUM_LENGTH IS NULL THEN '' ELSE ' (' + CONVERT(VARCHAR(10), CHARACTER_MAXIMUM_LENGTH) + ')' END + 
	   CASE WHEN IS_NULLABLE = 'NO' THEN ' not null' ELSE '' END AS CAMPOS
FROM INFORMATION_SCHEMA.COLUMNS 



select 
STUFF((SELECT ', '+isnull(CAMPOS, 'X')
   FROM VW_ESTRUTURA_TABELA
    WHERE TABELA = 'CPA'
	ORDER BY POSICAO
    FOR XML PATH('')),1,1,'') 